### ISSUE TITLE
Create a README.md for the project

### ISSUE THREAD

**Issue by kawaki-san** [kawaki-san/mirro-rs#2]
Look at some other repositories for ideas.

This [repo](https://github.com/amplication/amplication#readme) has a nice README

**Comment by kawaki-san** [comment]
Added with cddaf0a130ad9a19b3c3a5daa65de5a3d1b313ab

**Comment by istudyatuni** [comment]
Hey @kawaki-san, main page if this repo with README consuming 3-4 GB of RAM on Chrome, Linux :scream: (in Firefox only 600 MB)
